## 1 Importar librerias

In [1]:
#importa numpy
import numpy as np
#importa pandas
import pandas as pd

In [2]:
#Gráficos
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

## 2 Dataset

In [3]:
df = pd.read_csv('flights.csv', delimiter=',')  

# Mostrar todas las columnas y el ancho completo al imprimir DataFrames
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

df = pd.read_csv('flights.csv')

# Muestra información general sobre el DataFrame, incluyendo el tipo de datos de cada columna y la cantidad de valores no nulos.
print("info")
df.info()  

print("df")
df

info
<class 'pandas.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 21 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              336776 non-null  int64
 1   year            336776 non-null  int64
 2   month           336776 non-null  int64
 3   day             336776 non-null  int64
 4   dep_time        328521 non-null  float64
 5   sched_dep_time  336776 non-null  int64
 6   dep_delay       328521 non-null  float64
 7   arr_time        328063 non-null  float64
 8   sched_arr_time  336776 non-null  int64
 9   arr_delay       327346 non-null  float64
 10  carrier         336776 non-null  str
 11  flight          336776 non-null  int64
 12  tailnum         334264 non-null  str
 13  origin          336776 non-null  str
 14  dest            336776 non-null  str
 15  air_time        327346 non-null  float64
 16  distance        336776 non-null  int64
 17  hour            336776 non-null  int64
 18  minute          336776 non-null  int64
 19  time_hour       336776 non-null  str
 20  name            336776 non-null  str
dtypes: float64(5), int64(10), str(6)
memory usage: 54.0 MB
df

,id,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,name
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,United Air Lines Inc.
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,United Air Lines Inc.
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,American Airlines Inc.
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,JetBlue Airways
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00,Endeavor Air Inc.
336772,336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00,Endeavor Air Inc.
336773,336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00,Envoy Air
336774,336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00,Envoy Air
336775,336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00,Envoy Air

In [4]:
print("Type")
type(df)

Type

pandas.DataFrame

In [5]:
# tipo de dato de cada columna
print("Tipos de daptos")
df.dtypes

Tipos de daptos

id                  int64
year                int64
month               int64
day                 int64
dep_time          float64
sched_dep_time      int64
dep_delay         float64
arr_time          float64
sched_arr_time      int64
arr_delay         float64
carrier               str
flight              int64
tailnum               str
origin                str
dest                  str
air_time          float64
distance            int64
hour                int64
minute              int64
time_hour             str
name                  str
dtype: object

In [6]:
# Devuelve una tupla con la cantidad de dimensiones del array/DataFrame (usualmente 2 para tablas).
print("Cantidad de dimensiones")
df.ndim

Cantidad de dimensiones

2

In [7]:
# Devuelve el número total de elementos (celdas) en el DataFrame (filas x columnas).
print("Número total de elementos")
df.size

Número total de elementos

7072296

In [8]:
# Devuelve una tupla con las dimensiones totales del DataFrame en formato (filas, columnas).
print("Dimensiones del DataFrame")
df.shape

Dimensiones del DataFrame

(336776, 21)

In [9]:
print("columnas")
df.columns

columnas

Index(['id', 'year', 'month', 'day', 'dep_time', 'sched_dep_time', 'dep_delay',
       'arr_time', 'sched_arr_time', 'arr_delay', 'carrier', 'flight',
       'tailnum', 'origin', 'dest', 'air_time', 'distance', 'hour', 'minute',
       'time_hour', 'name'],
      dtype='str')

In [10]:
# renombre de columnas del DataFrame a español
traducciones = {
    'id': 'id',
    'year': 'año',
    'month': 'mes',
    'day': 'día',
    'dep_time': 'hora salida',
    'sched_dep_time': 'hora salida programada',
    'dep_delay': 'retraso salida',
    'arr_time': 'hora llegada',
    'sched_arr_time': 'hora llegada programada',
    'arr_delay': 'retraso llegada',
    'carrier': 'aerolinea',
    'flight': 'vuelo',
    'tailnum': 'matricula',
    'origin': 'origen',
    'dest': 'destino',
    'air_time': 'tiempo vuelo',
    'distance': 'distancia',
    'hour': 'hora',
    'minute': 'minuto',
    'time_hour': 'hora fecha',
    'name': 'nombre'
}

df = df.rename(columns=traducciones)

print(df.columns)

Index(['id', 'año', 'mes', 'día', 'hora salida', 'hora salida programada',
       'retraso salida', 'hora llegada', 'hora llegada programada',
       'retraso llegada', 'aerolinea', 'vuelo', 'matricula', 'origen',
       'destino', 'tiempo vuelo', 'distancia', 'hora', 'minuto', 'hora fecha',
       'nombre'],
      dtype='str')

In [11]:
df

,id,año,mes,día,hora salida,hora salida programada,retraso salida,hora llegada,hora llegada programada,retraso llegada,aerolinea,vuelo,matricula,origen,destino,tiempo vuelo,distancia,hora,minuto,hora fecha,nombre
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,United Air Lines Inc.
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,United Air Lines Inc.
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,American Airlines Inc.
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,JetBlue Airways
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00,Endeavor Air Inc.
336772,336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00,Endeavor Air Inc.
336773,336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00,Envoy Air
336774,336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00,Envoy Air
336775,336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00,Envoy Air

#### Datos nulos

In [12]:
# Obtengo la cantidad de datos faltantes en cada columna
dfNull = df.isnull().sum()
print(dfNull)

id                            0
año                           0
mes                           0
día                           0
hora salida                8255
hora salida programada        0
retraso salida             8255
hora llegada               8713
hora llegada programada       0
retraso llegada            9430
aerolinea                     0
vuelo                         0
matricula                  2512
origen                        0
destino                       0
tiempo vuelo               9430
distancia                     0
hora                          0
minuto                        0
hora fecha                    0
nombre                        0
dtype: int64

In [13]:
# Obtengo el maximo valor de datos faltantes y lo guardo en la variable dfNullSumMax
dfNullSumMax = df.isnull().sum().max()

print(f"El valor máximo de datos faltantes es {dfNullSumMax}")

El valor máximo de datos faltantes es 9430

In [14]:
# Obtengo la cantidad de filas total y divido el maximo valor de datos faltantes por este numero y lo multiplico por 100

row_total= len(df)

Null100 = (dfNullSumMax / row_total) * 100
print(f"El porcentaje máximo de datos faltantes es {Null100}%")

El porcentaje máximo de datos faltantes es 2.800080765850298%

In [15]:
# Devuelve una Serie booleana indicando si cada celda es nula (True) o no (False).
df.isnull()

,id,año,mes,día,hora salida,hora salida programada,retraso salida,hora llegada,hora llegada programada,retraso llegada,aerolinea,vuelo,matricula,origen,destino,tiempo vuelo,distancia,hora,minuto,hora fecha,nombre
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,False,False,False,False,True,False,True,True,False,True,False,False,True,False,False,True,False,False,False,False,False
336772,False,False,False,False,True,False,True,True,False,True,False,False,True,False,False,True,False,False,False,False,False
336773,False,False,False,False,True,False,True,True,False,True,False,False,False,False,False,True,False,False,False,False,False
336774,False,False,False,False,True,False,True,True,False,True,False,False,False,False,False,True,False,False,False,False,False
336775,False,False,False,False,True,False,True,True,False,True,False,False,False,False,False,True,False,False,False,False,False

### Agrea categorías de demora

In [16]:


def clasificar_puntualidad(retraso):
    if pd.isna(retraso):
        return 'Desconocido'
    elif retraso < 0:
        return 'Adelantado'   
    elif retraso == 0:
        return 'A tiempo'    
    elif retraso < 10:
        return 'Aceptable'    
    elif retraso <= 20:
        return 'Moderado'    
    elif retraso <= 30:
        return 'Severo'    
    else:
        return 'Crítico'    
    
    
    
    # Crear la única columna con el string de estado
df['nivel_puntualidad'] = df['retraso llegada'].apply(clasificar_puntualidad)

# Tabla resumen con la cantidad y el porcentaje de cada estado
conteo = df['nivel_puntualidad'].value_counts()
porcentaje = df['nivel_puntualidad'].value_counts(normalize=True) * 100

tabla_puntualidad = pd.DataFrame(
    {'Cantidad de Vuelos': conteo, 'Porcentaje (%)': porcentaje.round(2)}
)

print('--- Distribución de Puntualidad ---')
print(tabla_puntualidad)

--- Distribución de Puntualidad ---
                   Cantidad de Vuelos  Porcentaje (%)
nivel_puntualidad
Adelantado                     188933           56.10
Crítico                         51499           15.29
Aceptable                       38010           11.29
Moderado                        28136            8.35
Severo                          15359            4.56
Desconocido                      9430            2.80
A tiempo                         5409            1.61

In [17]:
df

,id,año,mes,día,hora salida,hora salida programada,retraso salida,hora llegada,hora llegada programada,retraso llegada,aerolinea,vuelo,matricula,origen,destino,tiempo vuelo,distancia,hora,minuto,hora fecha,nombre,nivel_puntualidad
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,United Air Lines Inc.,Moderado
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,United Air Lines Inc.,Moderado
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,American Airlines Inc.,Crítico
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,JetBlue Airways,Adelantado
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.,Adelantado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00,Endeavor Air Inc.,Desconocido
336772,336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00,Endeavor Air Inc.,Desconocido
336773,336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00,Envoy Air,Desconocido
336774,336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00,Envoy Air,Desconocido
336775,336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00,Envoy Air,Desconocido

In [27]:
# Agrupamos por aerolínea y obtenemos las matrículas únicas de sus aviones
# Usamos unique() para que no se repitan si un avión voló muchas veces
aviones_por_aerolinea = df.groupby('aerolinea')['matricula'].unique()

print("--- Lista de Aerolíneas y sus Matrículas de Aviones ---")
for aerolinea, matriculas in aviones_por_aerolinea.items():
    print(f"\n Aerolínea: {aerolinea}")
    print(f"   Total de aviones únicos: {len(matriculas)}")
    print(f"   Matrículas: {list(matriculas)}")

--- Lista de Aerolíneas y sus Matrículas de Aviones ---

 Aerolínea: 9E
   Total de aviones únicos: 204
   Matrículas: ['N915XJ', 'N8444F', 'N920XJ', 'N8409N', 'N8631E', 'N913XJ', 'N904XJ', 'N934XJ', 'N910XJ', 'N931XJ', 'N8968E', 'N604LR', 'N8515F', 'N906XJ', 'N8894A', 'N908XJ', 'N925XJ', 'N8611A', 'N905XJ', 'N8598B', 'N836AY', 'N602LR', 'N916XJ', 'N924XJ', 'N8946A', 'N902XJ', 'N8869B', 'N901XJ', 'N841AY', 'N829AY', 'N918XJ', 'N930XJ', 'N812AY', 'N8783E', 'N8432A', 'N8501F', 'N8908D', 'N8416B', 'N8390A', 'N933XJ', 'N601LR', 'N922XJ', 'N8646A', 'N600LR', 'N907XJ', 'N839AY', 'N820AY', 'N8412F', 'N8516C', 'N605LR', 'N919XJ', 'N8976E', 'N8794B', 'N914XJ', 'N8492C', 'N8877A', 'N8475B', 'N602XJ', 'N8940E', 'N826AY', 'N8924B', 'N8974C', 'N909XJ', 'N8884E', 'N8836A', 'N833AY', 'N917XJ', 'N903XJ', 'N8506C', 'N928XJ', 'N232PQ', 'N8525B', 'N827AY', 'N8914A', 'N8855A', 'N187PQ', 'N921XJ', 'N8710A', 'N937XJ', 'N8903A', 'N932XJ', 'N8948B', 'N8828D', 'N8659B', 'N8674A', 'N8932C', 'N929XJ', 'N8886A', 'N8970D', nan, 'N8747B', 'N8921B', 'N912XJ', 'N923XJ', 'N835AY', 'N8751D', 'N8980A', 'N8936A', 'N8672A', 'N8943A', 'N8883E', 'N8577D', 'N8554A', 'N8423C', 'N8913A', 'N8896A', 'N8847A', 'N146PQ', 'N8907A', 'N8837B', 'N8505Q', 'N8944B', 'N936XJ', 'N8688C', 'N153PQ', 'N824AY', 'N805AY', 'N823AY', 'N8971A', 'N935XJ', 'N8918B', 'N8458A', 'N8964E', 'N8888D', 'N161PQ', 'N8965E', 'N831AY', 'N834AY', 'N8905F', 'N801AY', 'N8604C', 'N8969A', 'N8808H', 'N170PQ', 'N8623A', 'N8797A', 'N825AY', 'N800AY', 'N8533D', 'N8694A', 'N8698A', 'N181PQ', 'N8800G', 'N819AY', 'N8709A', 'N8758D', 'N830AY', 'N8930E', 'N8495B', 'N8580A', 'N926XJ', 'N8775A', 'N8718E', 'N8696C', 'N8891A', 'N8736A', 'N8488D', 'N8923A', 'N8933B', 'N8982A', 'N176PQ', 'N8477R', 'N8790A', 'N8673D', 'N228PQ', 'N8683B', 'N840AY', 'N8541D', 'N601XJ', 'N832AY', 'N8588D', 'N8839E', 'N8543F', 'N8960A', 'N200PQ', 'N8972E', 'N8532G', 'N8665A', 'N197PQ', 'N162PQ', 'N821AY', 'N8587E', 'N927XJ', 'N8560F', 'N8938A', 'N8745B', 'N292PQ', 'N8977A', 'N8928A', 'N8771A', 'N8733G', 'N813AY', 'N8942A', 'N8721B', 'N293PQ', 'N279PQ', 'N294PQ', 'N272PQ', 'N295PQ', 'N8986B', 'N296PQ', 'N297PQ', 'N298PQ', 'N299PQ']

 Aerolínea: AA
   Total de aviones únicos: 601
   Matrículas: ['N619AA', 'N3ALAA', 'N3DUAA', 'N633AA', 'N3EMAA', 'N3BAAA', 'N3CYAA', 'N3GKAA', 'N4WNAA', 'N5FMAA', 'N3EKAA', 'N3ETAA', 'N541AA', 'N4WRAA', 'N4WPAA', 'N338AA', 'N336AA', 'N3HMAA', 'N3GEAA', 'N573AA', 'N3GVAA', 'N4YCAA', 'N3BDAA', 'N5FSAA', 'N324AA', 'N5EXAA', 'N5CRAA', 'N517AA', 'N596AA', 'N4WJAA', 'N3FXAA', 'N328AA', 'N325AA', 'N581AA', 'N3AVAA', 'N3GSAA', 'N3DEAA', 'N3EYAA', 'N322AA', 'N426AA', 'N545AA', 'N3EGAA', 'N3BUAA', 'N3FTAA', 'N511AA', 'N544AA', 'N5DMAA', 'N339AA', 'N3CFAA', 'N4UCAA', 'N5EWAA', 'N589AA', 'N3HYAA', 'N342AA', 'N319AA', 'N3CGAA', 'N569AA', 'N3DYAA', 'N630AA', 'N3BYAA', 'N565AA', 'N5DRAA', 'N3CAAA', 'N3FUAA', 'N3CVAA', 'N539AA', 'N386AA', 'N377AA', 'N3AXAA', 'N3FMAA', 'N3DWAA', 'N594AA', 'N3ESAA', 'N5BYAA', 'N332AA', 'N323AA', 'N3CUAA', 'N4XFAA', 'N327AA', 'N3BNAA', 'N5DNAA', 'N3EHAA', 'N3EVAA', 'N621AA', 'N3BEAA', 'N3CRAA', 'N5ELAA', 'N5EUAA', 'N436AA', 'N3JJAA', 'N528AA', 'N455AA', 'N3CNAA', 'N487AA', 'N5FTAA', 'N593AA', 'N3JPAA', 'N5ENAA', 'N546AA', 'N3DFAA', 'N3JMAA', 'N3BXAA', 'N3DLAA', 'N548AA', 'N578AA', 'N3BHAA', 'N4XRAA', 'N3FBAA', 'N3AUAA', 'N5CYAA', 'N3GDAA', 'N554AA', 'N4XTAA', 'N3FYAA', 'N3HLAA', 'N344AA', 'N3CKAA', 'N437AA', 'N4WTAA', 'N3HPAA', 'N3BTAA', 'N631AA', 'N557AA', 'N3CWAA', 'N371AA', 'N598AA', 'N5FFAA', 'N3FPAA', 'N3DNAA', 'N590AA', 'N3ENAA', 'N3GRAA', 'N3CEAA', 'N3GCAA', nan, 'N618AA', 'N638AA', 'N3ADAA', 'N3ERAA', 'N5ETAA', 'N556AA', 'N5FJAA', 'N3EWAA', 'N612AA', 'N201AA', 'N513AA', 'N3BLAA', 'N494AA', 'N3HFAA', 'N3HCAA', 'N3ACAA', 'N4WAAA', 'N3HVAA', 'N492AA', 'N3FVAA', 'N3JHAA', 'N3GUAA', 'N514AA', 'N5FAAA', 'N579AA', 'N564AA', 'N3BKAA', 'N542AA', 'N3HKAA', 'N396AA', 'N480AA', 'N3CXAA', 'N3JAAA', 'N5CCAA', 'N357AA', 'N552AA', 'N617AA', 'N3AFAA', 'N3ELAA', 'N3GYAA', 'N3AMAA', 'N3GXAA', 'N5DVAA', 'N5BSAA', 'N3DGAA', 'N3DVAA', 'N582AA', 'N4YJAA', 'N553AA', 'N4WWAA', 'N3JEAA', 'N3ASAA', 'N584AA', 'N566AA', 'N467AA', 'N456AA', 'N3BRAA', 'N501AA', 'N522AA', 'N3GLAA', 'N5FNAA', 'N3ANAA', 'N3AHAA', 'N3HXAA', 'N373AA', 'N4WKAA', 'N3GFAA', 'N3FJAA', 'N3JDAA', 'N358AA', 'N3JTAA', 'N3FAAA', 'N515AA', 'N3BGAA', 'N200AA', 'N5DBAA', 'N5ECAA', 'N3HBAA', 'N5EHAA', 'N7BFAA', 'N470AA', 'N3FLAA', 'N4XWAA', 'N3CHAA', 'N575AA', 'N3FHAA', 'N439AA', 'N329AA', 'N466AA', 'N3HNAA', 'N385AA', 'N4UBAA', 'N615AA', 'N4YEAA', 'N433AA', 'N4XJAA', 'N639AA', 'N3DBAA', 'N335AA', 'N5BRAA', 'N320AA', 'N3GAAA', 'N5DCAA', 'N5BVAA', 'N540AA', 'N3DSAA', 'N5EGAA', 'N3GNAA', 'N3JRAA', 'N3DCAA', 'N3GBAA', 'N577AA', 'N551AA', 'N471AA', 'N478AA', 'N3GGAA', 'N591AA', 'N597AA', 'N3CLAA', 'N364AA', 'N483AA', 'N4WLAA', 'N5DSAA', 'N4XSAA', 'N3JSAA', 'N363AA', 'N354AA', 'N5EBAA', 'N4YLAA', 'N3GMAA', 'N3EUAA', 'N3DAAA', 'N5DTAA', 'N473AA', 'N3JLAA', 'N628AA', 'N4XEAA', 'N4XVAA', 'N4XNAA', 'N475AA', 'N3GJAA', 'N3EFAA', 'N3DPAA', 'N3BMAA', 'N3FSAA', 'N4YUAA', 'N4XBAA', 'N3CJAA', 'N625AA', 'N3BBAA', 'N356AA', 'N3FFAA', 'N3ARAA', 'N3JUAA', 'N474AA', 'N3JBAA', 'N3GWAA', 'N512AA', 'N3GTAA', 'N476AA', 'N3ATAA', 'N481AA', 'N469AA', 'N384AA', 'N3BCAA', 'N3BWAA', 'N536AA', 'N3CDAA', 'N5EAAA', 'N361AA', 'N5DUAA', 'N570AA', 'N3ABAA', 'N491AA', 'N5CBAA', 'N5CDAA', 'N3JNAA', 'N583AA', 'N3CCAA', 'N484AA', 'N5CSAA', 'N5CKAA', 'N5CFAA', 'N4XMAA', 'N5FLAA', 'N4XYAA', 'N352AA', 'N3DXAA', 'N576AA', 'N348AA', 'N5DWAA', 'N362AA', 'N3EJAA', 'N4YHAA', 'N3BJAA', 'N4WSAA', 'N3BVAA', 'N3FRAA', 'N3APAA', 'N4YGAA', 'N5DEAA', 'N4YKAA', 'N3BFAA', 'N5FPAA', 'N395AA', 'N3BSAA', 'N599AA', 'N351AA', 'N3JWAA', 'N3DHAA', 'N3HAAA', 'N3ECAA', 'N3DMAA', 'N4YMAA', 'N5EYAA', 'N499AA', 'N4XDAA', 'N434AA', 'N399AA', 'N3HUAA', 'N345AA', 'N3JGAA', 'N438AA', 'N634AA', 'N3AKAA', 'N4YAAA', 'N5DXAA', 'N4XPAA', 'N3EAAA', 'N5CAAA', 'N486AA', 'N5EVAA', 'N5EJAA', 'N525AA', 'N595AA', 'N4YBAA', 'N454AA', 'N5CPAA', 'N521AA', 'N3HEAA', 'N3EPAA', 'N343AA', 'N3AAAA', 'N5DDAA', 'N3DDAA', 'N5EKAA', 'N509AA', 'N390AA', 'N3AWAA', 'N3FWAA', 'N585AA', 'N3GPAA', 'N567AA', 'N394AA', 'N3CTAA', 'N5DYAA', 'N349AA', 'N3AJAA', 'N3EXAA', 'N5FKAA', 'N3FEAA', 'N4YFAA', 'N3FDAA', 'N529AA', 'N568AA', 'N374AA', 'N3JFAA', 'N571AA', 'N547AA', 'N3EBAA', 'N488AA', 'N635AA', 'N518AA', 'N3JKAA', 'N5FHAA', 'N4YRAA', 'N3HDAA', 'N3FCAA', 'N4XUAA', 'N519AA', 'N538AA', 'N3HJAA', 'N4YTAA', 'N624AA', 'N477AA', 'N560AA', 'N5BTAA', 'N559AA', 'N5EEAA', 'N3AGAA', 'N5FGAA', 'N4XLAA', 'N4WVAA', 'N5CGAA', 'N202AA', 'N490AA', 'N388AA', 'N3HRAA', 'N505AA', 'N574AA', 'N4XXAA', 'N3JCAA', 'N527AA', 'N3BPAA', 'N592AA', 'N3EDAA', 'N3HWAA', 'N4XHAA', 'N3DRAA', 'N622AA', 'N493AA', 'N5FRAA', 'N425AA', 'N370AA', 'N468AA', 'N435AA', 'N4YNAA', 'N550AA', 'N365AA', 'N4XKAA', 'N3FKAA', 'N360AA', 'N3HGAA', 'N355AA', 'N3AYAA', 'N4XCAA', 'N613AA', 'N383AA', 'N4WYAA', 'N4XGAA', 'N4WMAA', 'N543AA', 'N5DPAA', 'N520AA', 'N587AA', 'N380AA', 'N3CBAA', 'N3FGAA', 'N5EPAA', 'N5EFAA', 'N4YPAA', 'N530AA', 'N4YSAA', 'N391AA', 'N5CEAA', 'N640AA', 'N3GHAA', 'N489AA', 'N526AA', 'N3CSAA', 'N393AA', 'N472AA', 'N496AA', 'N3FNAA', 'N3CPAA', 'N642AA', 'N346AA', 'N3EEAA', 'N3HSAA', 'N5DFAA', 'N561AA', 'N398AA', 'N537AA', 'N424AA', 'N5CLAA', 'N482AA', 'N3JVAA', 'N3DJAA', 'N381AA', 'N3HHAA', 'N508AA', 'N503AA', 'N3JXAA', 'N586AA', 'N3DTAA', 'N4YDAA', 'N5EMAA', 'N3KGAA', 'N3KAAA', 'N397AA', 'N3HTAA', 'N3KYAA', 'N3KUAA', 'N387AA', 'N504AA', 'N3KJAA', 'N3JYAA', 'N3KNAA', 'N3KSAA', 'N353AA', 'N3AEAA', 'N3KVAA', 'N3KLAA', 'N347AA', 'N502AA', 'N3KEAA', 'N3KCAA', 'N3KKAA', 'N3KWAA', 'N3LBAA', 'N479AA', 'N3KPAA', 'N3KHAA', 'N3CMAA', 'N485AA', 'N5FDAA', 'N3KMAA', 'N555AA', 'N3KTAA', 'N366AA', 'N403AA', 'N369AA', 'N5FEAA', 'N3KRAA', 'N375AA', 'N558AA', 'N3KDAA', 'N3KXAA', 'N368AA', 'N3KBAA', 'N623AA', 'N549AA', 'N376AA', 'N5CHAA', 'N367AA', 'N379AA', 'N3KFAA', 'N392AA', 'N359AA', 'N372AA', 'N378AA', 'N389AA', 'N382AA', 'N5CNAA', 'N3LAAA', 'N7AYAA', 'N5DLAA', 'N5DHAA', 'N7AAAA', 'N3LEAA', 'N3LGAA', 'N3LFAA', 'N7BMAA', 'N3LDAA', 'N5FBAA', 'N5DAAA', 'N516AA', 'N506AA', 'N7AEAA', 'N7ACAA', 'N7AXAA', 'N5DKAA', 'N7BAAA', 'N350AA', 'N7BVAA', 'N580AA', 'N7ASAA', 'N5EDAA', 'N5DJAA', 'N7ALAA', 'N7BGAA', 'N5ESAA', 'N7BKAA', 'N7CAAA', 'N5FCAA', 'N5ERAA']

 Aerolínea: AS
   Total de aviones únicos: 84
   Matrículas: ['N594AS', 'N553AS', 'N592AS', 'N552AS', 'N533AS', 'N579AS', 'N546AS', 'N558AS', 'N568AS', 'N551AS', 'N537AS', 'N408AS', 'N407AS', 'N563AS', 'N403AS', 'N513AS', 'N402AS', 'N508AS', 'N320AS', 'N565AS', 'N531AS', 'N596AS', 'N589AS', 'N506AS', 'N518AS', 'N535AS', 'N597AS', 'N556AS', 'N305AS', 'N577AS', 'N548AS', 'N529AS', 'N549AS', 'N307AS', 'N323AS', 'N584AS', 'N523AS', 'N583AS', 'N520AS', 'N526AS', 'N419AS', 'N423AS', 'N409AS', 'N524AS', 'N517AS', 'N413AS', 'N538AS', 'N306AS', 'N303AS', 'N512AS', 'N431AS', 'N433AS', 'N440AS', 'N435AS', 'N319AS', 'N442AS', 'N514AS', 'N528AS', 'N593AS', 'N532AS', 'N569AS', 'N519AS', 'N590AS', 'N530AS', 'N562AS', 'N302AS', 'N585AS', 'N566AS', 'N581AS', 'N587AS', 'N309AS', 'N570AS', 'N559AS', 'N318AS', 'N516AS', 'N527AS', 'N525AS', 'N586AS', 'N315AS', 'N534AS', 'N564AS', 'N536AS', 'N560AS', 'N557AS']

 Aerolínea: B6
   Total de aviones únicos: 193
   Matrículas: ['N804JB', 'N516JB', 'N593JB', 'N793JB', 'N657JB', 'N708JB', 'N595JB', 'N644JB', 'N635JB', 'N794JB', 'N709JB', 'N805JB', 'N796JB', 'N558JB', 'N178JB', 'N646JB', 'N779JB', 'N651JB', 'N562JB', 'N304JB', 'N563JB', 'N552JB', 'N625JB', 'N633JB', 'N624JB', 'N645JB', 'N206JB', 'N273JB', 'N570JB', 'N228JB', 'N527JB', 'N521JB', 'N292JB', 'N274JB', 'N564JB', 'N184JB', 'N281JB', 'N203JB', 'N568JB', 'N216JB', 'N346JB', 'N580JB', 'N775JB', 'N534JB', 'N508JB', 'N503JB', 'N579JB', 'N615JB', 'N806JB', 'N306JB', 'N565JB', 'N529JB', 'N520JB', 'N630JB', 'N279JB', 'N590JB', 'N652JB', 'N612JB', 'N239JB', 'N192JB', 'N537JB', 'N636JB', 'N510JB', 'N504JB', 'N231JB', 'N607JB', 'N316JB', 'N712JB', 'N599JB', 'N190JB', 'N665JB', 'N507JB', 'N618JB', 'N329JB', 'N661JB', 'N658JB', 'N663JB', 'N294JB', 'N592JB', 'N569JB', 'N505JB', 'N523JB', 'N559JB', 'N632JB', 'N640JB', 'N267JB', 'N536JB', 'N535JB', 'N587JB', 'N603JB', 'N307JB', 'N198JB', 'N284JB', 'N608JB', 'N547JB', 'N531JB', 'N594JB', 'N639JB', 'N591JB', 'N588JB', 'N637JB', 'N629JB', 'N807JB', 'N766JB', 'N656JB', 'N236JB', 'N583JB', 'N506JB', 'N337JB', 'N703JB', 'N509JB', 'N309JB', 'N339JB', 'N586JB', 'N589JB', 'N353JB', 'N706JB', 'N621JB', 'N655JB', 'N784JB', 'N187JB', 'N613JB', 'N524JB', 'N760JB', 'N324JB', 'N556JB', 'N519JB', 'N597JB', 'N809JB', 'N729JB', 'N662JB', 'N746JB', 'N265JB', 'N606JB', 'N821JB', 'N283JB', 'N789JB', 'N763JB', 'N526JB', 'N296JB', 'N351JB', 'N585JB', 'N768JB', 'N641JB', 'N584JB', 'N249JB', 'N648JB', 'N229JB', 'N328JB', 'N517JB', 'N634JB', 'N193JB', 'N554JB', 'N659JB', 'N317JB', 'N179JB', 'N705JB', 'N561JB', 'N323JB', 'N643JB', 'N653JB', 'N183JB', 'N571JB', 'N247JB', 'N649JB', 'N334JB', 'N298JB', 'N566JB', 'N348JB', 'N197JB', 'N318JB', 'N605JB', 'N598JB', 'N627JB', 'N638JB', 'N623JB', 'N715JB', 'N266JB', 'N258JB', 'N238JB', 'N355JB', 'N354JB', 'N373JB', 'N374JB', 'N368JB', 'N358JB', 'N827JB', 'N828JB', 'N834JB', 'N375JB', 'N903JB', 'N907JB', 'N913JB']

 Aerolínea: DL
   Total de aviones únicos: 629
   Matrículas: ['N668DN', 'N971DL', 'N3739P', 'N326NB', 'N327NW', 'N3763D', 'N705TW', 'N997DL', 'N318NB', 'N6703D', 'N998DL', 'N3760C', 'N325US', 'N935DL', 'N955DL', 'N317US', 'N947DL', 'N308DE', 'N349NW', 'N375NC', 'N324US', 'N900PC', 'N926DL', 'N361NB', 'N646DL', 'N970DL', 'N321NB', 'N371NB', 'N360NB', 'N713TW', 'N951DL', 'N975DL', 'N900DE', 'N956DL', 'N965DL', 'N933DL', 'N399DA', 'N3748Y', 'N920DE', 'N917DL', 'N339NW', 'N320NB', 'N376NW', 'N343NB', 'N999DN', 'N712TW', 'N969DL', 'N904DL', 'N342NB', 'N920DL', 'N711ZX', 'N670DN', 'N644DL', 'N3736C', 'N318US', 'N344NB', 'N6704Z', 'N327NB', 'N722TW', 'N319NB', 'N702TW', 'N678DL', 'N378NW', 'N372DA', 'N3750D', 'N688DL', 'N994DL', 'N918DE', 'N374DA', 'N301NB', 'N362NW', 'N704X', 'N361NW', 'N331NW', 'N980DL', 'N3730B', 'N723TW', 'N3761R', 'N369NW', 'N643DL', 'N359NB', 'N337NW', 'N3772H', 'N173DZ', 'N329NW', 'N3758Y', 'N727TW', 'N922DL', 'N6710E', 'N633DL', 'N375DA', 'N624AG', 'N3764D', 'N3740C', 'N3738B', 'N366NB', 'N618DL', 'N387DA', 'N915DE', 'N304DQ', 'N912DE', 'N339NB', 'N974DL', 'N541US', 'N3768', 'N989DL', 'N660DL', 'N918DL', 'N995DL', 'N322US', 'N358NW', 'N328NW', 'N305DQ', 'N335NW', 'N3743H', 'N336NB', 'N338NB', 'N710TW', 'N348NB', 'N665DN', 'N988DL', 'N936DL', 'N372NW', 'N707TW', 'N905DE', 'N337NB', 'N675DL', 'N940DL', 'N370NW', 'N983DL', 'N325NB', 'N323NB', 'N908DL', 'N927DA', 'N3751B', 'N679DA', 'N334NB', 'N301DQ', 'N973DL', 'N721TW', 'N364NB', 'N320US', 'N521US', 'N718TW', 'N360NW', 'N385DN', 'N322NB', 'N371DA', 'N977DL', 'N3745B', 'N312US', 'N6707A', 'N380DA', 'N3754A', 'N717TW', 'N346NB', 'N613DL', 'N658DL', 'N178DZ', 'N703TW', 'N3752', 'N335NB', 'N948DL', 'N637DL', 'N689DL', 'N369NB', 'N389DA', 'N368NW', 'N954DL', 'N641DL', 'N365NB', 'N324NB', 'N604DL', 'N348NW', 'N316NB', 'N699DL', 'N326US', 'N925DL', 'N307DQ', 'N396DA', 'N356NW', 'N332NW', 'N603DL', 'N302NB', 'N674DL', 'N3756', 'N938DL', 'N358NB', 'N306DQ', 'N692DL', 'N397DA', 'N949DL', 'N555NW', 'N354NW', 'N374NW', 'N3767', 'N392DA', 'N355NW', 'N3753', 'N648DL', 'N961DL', 'N363NW', 'N386DA', 'N303DQ', 'N923DL', 'N181DN', 'N317NB', 'N3734B', 'N3769L', 'N3765', 'N991DL', 'N341NB', 'N338NW', 'N329NB', 'N638DL', 'N342NW', 'N347NB', 'N377NW', 'N967DL', 'N904DE', 'N627DL', 'N979DL', 'N315US', 'N623DL', 'N379DA', 'N659DL', 'N909DL', 'N357NB', 'N706TW', 'N651DL', 'N319US', 'N309US', 'N336NW', 'N3757D', 'N394DA', 'N310DE', 'N3771K', 'N990DL', 'N371NW', 'N919DL', 'N344NW', 'N609DL', 'N907DL', 'N3744F', 'N835MH', 'N635DL', 'N905DL', 'N911DL', 'N175DN', 'N636DL', 'N908DE', 'N540US', 'N964DL', 'N3733Z', 'N523US', 'N357NW', 'N382DA', 'N919DE', 'N3731T', 'N373NW', 'N590NW', 'N906DL', 'N321US', 'N381DN', 'N3759', 'N347NW', 'N180DN', 'N543US', 'N617DL', 'N664DN', 'N934DL', 'N353NB', 'N350NA', 'N916DN', 'N944DL', 'N366NW', 'N610DL', 'N996DL', 'N645DL', 'N316US', 'N391DA', 'N349NB', 'N1613B', 'N398DA', 'N663DN', 'N690DL', 'N353NW', 'N340NB', 'N6712B', 'N3773D', 'N912DL', 'N642DL', 'N3755D', 'N6711M', 'N662DN', 'N993DL', 'N367NW', 'N345NW', 'N3766', 'N351NW', 'N364NW', 'N6714Q', 'N309DE', 'N963DL', 'N333NW', 'N355NB', 'N186DN', 'N388DA', 'N945DL', 'N377DA', 'N693DL', 'N942DL', 'N680DA', 'N937DL', 'N924DL', 'N914DL', 'N928DL', 'N341NW', 'N376DA', 'N176DN', 'N652DL', 'N976DL', 'N1611B', 'N195DN', 'N3762Y', 'N334NW', 'N953DL', 'N302DQ', 'N909DE', 'N6701', 'N669DN', 'N365NW', 'N602DL', 'N3746H', 'N343NW', 'N383DN', 'N957DL', 'N687DL', 'N913DE', 'N323US', 'N37700', 'N952DL', 'N655DL', 'N330NW', 'N3749D', 'N1602', 'N612DL', 'N906DE', 'N345NB', 'N3747D', 'N695DL', 'N966DL', 'N315NB', 'N666DN', 'N548US', 'N393DA', 'N370NB', 'N654DL', 'N982DL', 'N67171', 'N667DN', 'N640DL', 'N314NB', 'N709TW', 'N556NW', 'N525US', 'N368NB', 'N3737C', 'N359NW', 'N174DZ', 'N930DL', 'N915DL', 'N373DA', 'N639DL', 'N554NW', 'N962DL', 'N1609', 'N649DL', 'N901DE', 'N950DL', 'N384DA', 'N696DL', 'N1201P', 'N959DL', 'N676DL', 'N767NC', 'N698DL', 'N912DN', 'N987DL', 'N1608', 'N672DL', 'N965DN', 'N616DL', 'N946DL', 'N907DE', 'N865DA', 'N352NW', 'N686DA', 'N3735D', 'N903DE', 'N931DL', 'N910DL', 'N542US', 'N978DL', 'N185DN', 'N671DN', 'N1605', 'N390DA', 'N697DL', 'N310NW', 'N913DL', 'N902DE', 'N661DN', 'N910DE', 'N929DN', 'N155DL', 'N914DE', 'N960DL', 'N981DL', 'N198DN', 'N332NB', 'N916DE', 'N378DA', 'N6715C', 'N917DE', 'N921DL', 'N551NW', 'N503US', 'N3732J', 'N519US', 'N694DL', 'N1612T', 'N968DL', 'N685DA', 'N176DZ', 'N911DA', 'N395DN', 'N916DL', 'N171DN', 'N984DL', 'N3741S', 'N992DL', 'N614DL', 'N6702', 'N175DZ', 'N986DL', 'N6700', 'N363NB', 'N311US', 'N770NC', 'N923DN', 'N169DZ', 'N191DN', 'N187DN', 'N178DN', 'N6705Y', 'N782NC', 'N958DL', 'N362NB', 'N182DN', 'N190DN', 'N985DL', 'N787NC', 'N684DA', 'N340NW', 'N1604R', 'N941DL', 'N650DL', 'N6716C', 'N911DE', 'N681DA', 'N16065', 'N762NC', 'N939DL', 'N773NC', 'N779NC', 'N6708D', 'N313US', 'N972DL', 'N193DN', 'N6706Q', 'N943DL', 'N314US', 'N557NW', 'N184DN', 'N188DN', 'N550NW', 'N929DL', 'N196DN', 'N766NC', 'N1200K', 'N333NB', 'N932DL', 'N197DN', 'N172DZ', 'N914DN', 'N192DN', 'N784NC', 'N179DN', 'N534US', 'N3742C', 'N189DN', 'N683DA', 'N172DN', 'N6709', 'N856NW', 'N6713Y', 'N194DN', 'N154DL', 'N171DZ', 'N174DN', 'N1603', 'N522US', 'N945DN', 'N673DL', 'N177DZ', 'N854NW', 'N935AT', 'N828MH', 'N780NC', 'N615DL', 'N199DN', 'N839MH', 'N809NW', 'N910DN', 'N177DN', 'N990AT', 'N594NW', 'N774NC', 'N553NW', 'N764NC', 'N977AT', 'N904DA', 'N531US', 'N953DN', 'N183DN', 'N786NC', 'N961DN', 'N156DL', 'N978AT', 'N989AT', 'N941DN', 'N682DA', 'N915DN', 'N979AT', 'N775NC', 'N928DN', 'N981AT', 'N933AT', 'N902DA', 'N829MH', 'N958DN', 'N1501P', 'N533US', 'N994AT', 'N647DL', 'N842MH', 'N863DA', 'N906DA', 'D942DN', 'N552NW', 'N907DA', 'N919DN', 'N1607B', 'N959DN', 'N1610D', 'N532US', 'N549US', 'N136DL', 'N507US', 'N608DA', 'N530US', 'N905DA', 'N501US', 'N932DN', 'N963DN', 'N831MH', 'N750AT', 'N964DN', 'N757AT', 'N903DA', 'N777NC', 'N670US', 'N944DN', 'N394DL', 'N351NB', 'N917DN', 'N675MC', 'N943DN', 'N920DN', 'N956DN', 'N960DN', 'N937DN', 'N955DN', 'N825MH', 'N328NB', 'N600TR', 'N137DL', 'N539US', 'N921DN', 'N330NB', 'N354NB', 'N838MH', 'N595NW', 'N837MH', 'N826MH', 'N331NB', 'N587NW', 'N352NB', 'N547US', 'N862DA', 'N851NW', 'N834MH', 'N962DN', 'N827MH', 'N844MH', 'N939DN', 'N841MH', 'N913DN', 'N121DE', 'N153DL', 'N845MH', 'N918DH', 'N957DN', 'N840MH', 'N152DL', 'N843MH', 'N933DN', 'N143DA']

 Aerolínea: EV
   Total de aviones únicos: 316

In [28]:
df

,id,año,mes,día,hora salida,hora salida programada,retraso salida,hora llegada,hora llegada programada,retraso llegada,aerolinea,vuelo,matricula,origen,destino,tiempo vuelo,distancia,hora,minuto,hora fecha,nombre,nivel_puntualidad
0,0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01 05:00:00,United Air Lines Inc.,Moderado
1,1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01 05:00:00,United Air Lines Inc.,Moderado
2,2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01 05:00:00,American Airlines Inc.,Crítico
3,3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01 05:00:00,JetBlue Airways,Adelantado
4,4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01 06:00:00,Delta Air Lines Inc.,Adelantado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,3393,NaN,JFK,DCA,NaN,213,14,55,2013-09-30 14:00:00,Endeavor Air Inc.,Desconocido
336772,336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,3525,NaN,LGA,SYR,NaN,198,22,0,2013-09-30 22:00:00,Endeavor Air Inc.,Desconocido
336773,336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30 12:00:00,Envoy Air,Desconocido
336774,336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30 11:00:00,Envoy Air,Desconocido
336775,336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30 08:00:00,Envoy Air,Desconocido

In [30]:


# Yabla cruzada entre Aerolínea y Estado de Vuelo
tabla_resumen = pd.crosstab(
    df['aerolinea'], 
    df['nivel_puntualidad'], 
    margins=True,          
    margins_name='Total Vuelos'
)

print("Resumen general de vuelos y estados por aerolínea ---")
print(tabla_resumen)

Resumen general de vuelos y estados por aerolínea ---
nivel_puntualidad  A tiempo  Aceptable  Adelantado  Crítico  Desconocido  \
aerolinea
9E                      227       1602       10430     3099         1166
AA                      472       3244       20769     3827          782
AS                        8         54         512       62            5
B6                      926       6508       29514     9421          586
DL                      782       5348       30463     5533          452
EV                      801       5789       25823    11666         3065
F9                       18         86         271      171            4
FL                       69        543        1211      665           85
HA                        4         32         241       19            0
MQ                      488       3297       12856     4437         1360
OO                        0          3          19        6            3
UA                      918       6585       34642     7878          883
US                      369       2690       12113     2048          705
VX                       94        572        3276      615           46
WN                      227       1602        6513     1926          231
YV                        6         55         280      126           57
Total Vuelos           5409      38010      188933    51499         9430

nivel_puntualidad  Moderado  Severo  Total Vuelos
aerolinea
9E                     1229     707         18460
AA                     2349    1286         32729
AS                       51      22           714
B6                     4895    2785         54635
DL                     3752    1780         48110
EV                     4375    2654         54173
F9                       84      51           685
FL                      445     242          3260
HA                       33      13           342
MQ                     2633    1326         26397
OO                        0       1            32
UA                     4962    2797         58665
US                     1730     881         20536
VX                      366     193          5162
WN                     1178     598         12275
YV                       54      23           601
Total Vuelos          28136   15359        336776

In [ ]:

tabla_aviones = df.groupby(['aerolinea', 'matricula']).agg(
    total_vuelos_avion=('id', 'count'),
    media_retraso_llegada=('retraso llegada', 'mean'),
    media_retraso_salida=('retraso salida', 'mean')
).reset_index()

# redondeo de decimales
tabla_aviones['media_retraso_llegada'] = tabla_aviones['media_retraso_llegada'].round(2)
tabla_aviones['media_retraso_salida'] = tabla_aviones['media_retraso_salida'].round(2)

print("\n Desglose por Avión (Matrícula) y su Media de Retraso ---")
print(tabla_aviones.to_string(index=False)) # to_string(index=False) hace que se vea limpia como tabla en consola

 Desglose por Avión (Matrícula) y su Media de Retraso ---